apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: postgres
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgres
    spec:
      securityContext:
        runAsUser: 999
      restartPolicy: Always
      containers:
        - image: zerofudge/postgres:9.6
          imagePullPolicy: IfNotPresent
          name: db
          ports:
            - containerPort: 5432
